# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-44f45ba6-d512-4baf-a9e0-c93b93ba2972";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-44f45ba6-d512-4baf-a9e0-c93b93ba2972".device = "/dev/disk/by-uuid/44f45ba6-d512-4baf-a9e0-c93b93ba2972";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C167-2CF2";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # GPU específica desta máquina (opções: "intel", "nvidia", "hybrid-intel-nvidia", "amd")
  myHardware.gpu.type = lib.mkDefault "intel";
}
