$background = 131314
$onBackground = e4e2e2
$surface = 131314
$surfaceDim = 131314
$surfaceBright = 39393a
$surfaceContainerLowest = 0e0e0f
$surfaceContainerLow = 1b1c1c
$surfaceContainer = 1f2020
$surfaceContainerHigh = 2a2a2b
$surfaceContainerHighest = 343535
$onSurface = e4e2e2
$surfaceVariant = 43474a
$onSurfaceVariant = c3c7ca
$outline = 8d9195
$outlineVariant = 43474a
$inverseSurface = e4e2e2
$inverseOnSurface = 303031
$shadow = 000000
$scrim = 000000
$surfaceTint = b9c9d3
$primary = b9c9d3
$primaryDim = e3f3fe
$onPrimary = 24323a
$primaryContainer = 52616a
$onPrimaryContainer = ccdce6
$inversePrimary = 516069
$primaryFixed = d5e5ef
$primaryFixedDim = b9c9d3
$onPrimaryFixed = 0e1d25
$onPrimaryFixedVariant = 3a4951
$secondary = c2c7cb
$secondaryDim = dee3e8
$onSecondary = 2c3135
$secondaryContainer = 444a4e
$onSecondaryContainer = b4b9bd
$secondaryFixed = dee3e8
$secondaryFixedDim = c2c7cb
$onSecondaryFixed = 171c20
$onSecondaryFixedVariant = 42474b
$tertiary = d0c2d4
$tertiaryDim = f3e3f7
$onTertiary = 362d3b
$tertiaryContainer = 665b6b
$onTertiaryContainer = e3d4e7
$tertiaryFixed = eddef1
$tertiaryFixedDim = d0c2d4
$onTertiaryFixed = 211826
$onTertiaryFixedVariant = 4d4352
$error = ffb4ab
$errorDim = ff554a
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryPaletteKeyColor = 6a7982
$secondaryPaletteKeyColor = 72787c
$tertiaryPaletteKeyColor = 665b6b
$neutralPaletteKeyColor = 777777
$neutralVariantPaletteKeyColor = 74787b
$errorPaletteKeyColor = de3730
$primary_paletteKeyColor = 6a7982
$secondary_paletteKeyColor = 72787c
$tertiary_paletteKeyColor = 665b6b
$neutral_paletteKeyColor = 777777
$neutral_variant_paletteKeyColor = 74787b
$term0 = 343434
$term1 = 8383ff
$term2 = 41dff0
$term3 = 75fcdd
$term4 = 7cb2c8
$term5 = 7dadea
$term6 = 84d5e8
$term7 = ccdcd6
$term8 = 9aa59f
$term9 = a29eff
$term10 = 6fefff
$term11 = c9fff3
$term12 = a6c6d1
$term13 = a2c0f7
$term14 = 8ae9fd
$term15 = ffffff
$rosewater = f4f0fa
$flamingo = dfe0f5
$pink = c7dfff
$mauve = 85c6ff
$red = 8ab5ff
$maroon = abbef0
$peach = e0c2f9
$yellow = d0f9f4
$green = 9becff
$teal = ace9ff
$sky = a7e4ff
$sapphire = 81d1f8
$blue = 72c6f7
$lavender = 99d3fe
$klink = 1e91bf
$klinkSelection = 1c91be
$kvisited = 0086d1
$kvisitedSelection = 0087cf
$knegative = 607eff
$knegativeSelection = 607eff
$kneutral = c794ff
$kneutralSelection = c794ff
$kpositive = 00b9d6
$kpositiveSelection = 00bad5
$text = e4e2e2
$subtext1 = c3c7ca
$subtext0 = 8d9195
$overlay2 = 7b7e82
$overlay1 = 686b6e
$overlay0 = 57595c
$surface2 = 47484a
$surface1 = 363739
$surface0 = 252526
$base = 131314
$mantle = 131314
$crust = 121213
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
